### ISSUE TITLE
大佬, telegram推送拿不到chat id要怎么办...

### ISSUE THREAD

**Issue by woaihsw** [IvonWei/flexget_qbittorrent_mod#105]
配置如下, 容器里有pysocks

```
via:
          - telegram_mod:
              bot_token: xxxx:xxxx
              image: 'details_report.png'
              recipients:
                - username: 'xxxx'
              socks_proxy:
                url: socks5://172.17.0.1:1080
```

也给bot说过话了, 但还是报错no chat id found, try manually sending the bot any message to initialize the chat...

在容器里curl telegram的api是能正常推送内容到bot的...

```
{
"ok":true,
"result":
{"message_id":1120,"from":{"id":xxx,"is_bot":true,"first_name":"Bot","username":"xxxx_bot"},
"chat":
{"id":xxxx,"first_name":"xxxx","type":"private"},"date":xxxx,"text":"HelloWorld"}
}
```

之前同样的配置跑了两个多月...都没有问题...正常推送...

尝试调试一些小站的时候把数据库清掉了...

然后就没法推送了...
