### ISSUE TITLE
暂停做种的问题

### ISSUE THREAD

**Issue by woaihsw** [IvonWei/flexget_qbittorrent_mod#127]
是这样, 我想要实现一个定时检查种子的保种人数, 大于x就停止做种的效果, 配置如下:

```
resume:
    disable: [ seen, seen_info_hash, retry_failed, history ]
    if:
      - qbittorrent_state == 'pausedUP': accept  
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_resume_template

pause:
    disable: [ seen, seen_info_hash, retry_failed, history ]
    if:
      - qbittorrent_num_complete > X and qbittorrent_state == 'stalledUP':
          regexp:
            accept:
              - 'xxx'
            from: qbittorrent_tags
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_pause_template
```
然后让pause在resume五分钟后运行...

现在遇到的问题是, pause第一次执行会失败...

报错为:
```
WARNING  qbittorrent_client pause           Sync error, reset rid. reason: Duplicate operation detected: pause_torrents hash1|hash2|...
```

但是再运行一次又能成功...

所以现在的暂时解决方案是安排两次pause...

求教这是为什么...
