### ISSUE TITLE
limit returned entries from show_entry ?

### ISSUE THREAD

**Issue by oglops** [IvonWei/flexget_qbittorrent_mod#137]
因为这个flexget bug https://github.com/Flexget/Flexget/issues/3601, 暂时没法从命令行用 --dump accepted 了， 只好从webui用 show_entry， 可是他返回结果太多，可否加个 limit: int 来限制返回几个entry ? 或者说不改代码，从config里能直接达成么？

我现在用的是linuxserver的qb 4.5.0,  lz最新的flexget镜像 3.5.1 (2022-11-04) https://hub.docker.com/r/madwind/flexget, 系统是Fedora 37 使用的是podman 4.3.1

https://github.com/madwind/flexget_qbittorrent_mod/blob/1d4b9e5d9e13316b2949c41603dd7dcf0a9054e9/show_entry.py#L8-L14

这样可以就是有点麻烦 - 麻烦的点在于大部分task都是直接下面几个template, 如果我要这么测试，就得把所有output 的template 注释掉，贴下面这段，测试好再删这段，而不是直接comment/uncomment `show_one_entry_template`就好了那么容易
```yaml
    limit:
      amount: 10
      from:
        from_qbittorrent_mod: *qbittorrent_setting
```
因为limit 是个 input plugin，设想是 如果show_entry有limit property, 就可以这样用了
```yaml
  show_one_entry_template:
    show_entry:
      state: accepted
      attribute: yes
      limit: 1
```
这样在测试config的时候就不用改动结构，只要加上面这个template就可以了，比较方便
