### ISSUE TITLE
Sync error, reset rid. reason: not connected

### ISSUE THREAD

**Issue by tio-plato** [IvonWei/flexget_qbittorrent_mod#146]
按照config.example.yaml 配置好后，每个任务进行的时候都会刷大量的 ```Sync error, reset rid. reason: not connected``` 的 WARNING，但是实际上任务都能正常运行。
![image](https://github.com/madwind/flexget_qbittorrent_mod/assets/60922756/641eefab-d55b-467c-b516-3ff63cf8807b)

**Comment by madwind** [comment]
你的refresh任务 连不上qb

**Comment by tio-plato** [comment]
> 你的refresh任务 连不上qb

实际上能连上，所有任务执行之前都会刷一屏，但是任务最后都能执行成功。
yaml 里面的 qbittorrent 设置是:

```yaml
  qbittorrent_setting: &qbittorrent_setting
    host: qbittorrent
    port: 8080
    #非https请设置为 no
    use_ssl: no
```
通过docker内网连接的，并且qb设置了docker内网的免验证
