### ISSUE TITLE
脚本运行报错 Task does not have any filter plugins to accept entries

### ISSUE THREAD

**Issue by z4jst** [IvonWei/flexget_qbittorrent_mod#20]
大佬你好，在docker 上新建了flexget，运行正常，在目录中也放入了插件。
修改后的配置文件后运行报错
`2021-10-29 20:13:01
WARNING
task
modify
Task does not have any filter plugins to accept entries. You need at least one to accept the entries you want.
`
请问这个是什么原因导致的错误？谢谢
config文件如下：
```
web_server:
  bind: 0.0.0.0
  port: 3539

templates:
  from_qbittorrent_template:
    from_qbittorrent_mod: &qbittorrent_setting
      host: ****
      port: ****
      #非https请设置为 no
      use_ssl: no
      username: ****
      password: ****
  #基础
  qbittorrent_base_template:
    qbittorrent_mod: *qbittorrent_setting

  #修改
  qbittorrent_modify_template:
    qbittorrent_mod:
      action:
        modify:
          replace_trackers:
            #http替换成https
            'https://tracker.****.org/': 'http://tracker.****.org/'

schedules:
  - tasks: [ modify ]
    interval:
      #5分钟
      minutes: 5

tasks:
  modify:
    priority: 4
    disable: [ seen, seen_info_hash, retry_failed, history ]
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_modify_template
```
